version: '3.8'

services:
  web:
    build: .
    container_name: gefahrstoffe_app
    ports:
      - "5000:5000"
    volumes:
      # Mount the entire source code to persist git pull updates
      - ./:/app
      # Native Docker Volume to bypass LXC SQLite locking bug
      - gefahrstoff_db:/db
    restart: always

volumes:
  gefahrstoff_db:
